### ISSUE TITLE
Tutorial/Extended readme

### ISSUE THREAD

**Issue by Phreakyx** [Rolv-Arild/replay-pretraining#3]
If possible could you provide an explanation on how to properly install this project and start training a model. So far personally i managed to get all dependencies and install it as a python project but it seems to rely on files that are not in the repository and there are no comments on how exactly it should work nor an explanation on how to use it properly. This would be highly appreciated as I would really like to start training my own bot on replays rather than how others were trained. Thanks in advance. I am open to discuss on another platforms as well.

**Comment by Rolv-Arild** [comment]
I rewrote the entire repo. Hopefully it's easier to understand now.
